### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by BananeiroZika** [mportorodrigo/simple-python-adventure-game#1]
Apenas uma sugestão...
- [ ] Utilizar algum banco de dados ou algo similar para atribuir eventos e diminuir o código principal

**Comment by mportorodrigo** [comment]
@BananeiroZika - Agradeço a sugestão. Este projeto foi desenvolvido atendendo as necessidades de um trabalho para o curso do Udacity. Uma vez concluído o curso pretendo expandir este projeto e integrar um banco de dados.
